### ISSUE TITLE
fails with error

### ISSUE THREAD

**Issue by veeramarni** [snyamathi/lerna-semver-sync#1]
node: 8.4.0
npm: 5.3.0
lerna: 2.0.0
```
stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:98
    return /(\d+)/.exec(range)[0];
                              ^

TypeError: Cannot read property '0' of null
    at getMajorVersion (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:98:31)
    at compoundRange.split.map.forEach.range (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:76:34)
    at Array.forEach (<anonymous>)
    at compoundRanges.reduce (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:71:62)
    at Array.reduce (<anonymous>)
    at getCommonRange (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:70:42)
    at reduce (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lerna-semver-sync/lerna-semver-sync.js:92:24)
    at /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lodash/_baseReduce.js:18:9
    at /Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/workbench-stack/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/
```

**Comment by snyamathi** [comment]
I believe this is fixed in v1.3.0 but if not, please provide some more details so that I can reproduce.
